
[project]
name = "Class-Alert"
version = "0.1.2"
description = ""
readme = "README.md"
requires-python = ">=3.12.3,<3.13"
authors = [
    { name = "Zaim Maalim Sheali", email = "rehanamahmoud48@gmail.com" }
]
dependencies = [
    "flet==0.86.5",
    "flet-permission-handler",
    "pyjnius==1.7.0",
    "plyer",
    "android-notify",
    "flet-webview-all", 
]

[dependency-groups]
dev = [
    "flet-cli==0.86.5",
    "flet-desktop==0.86.5",
    "flet-web==0.86.5",
]

[tool.flet]
org = "org.digielimu"
product = "ClassAlert"
company = "Smart Elimu Connect"
copyright = "Copyright (C) 2026 by Digi Elimu"

[tool.flet.app]
path = "src"

[tool.flet.flutter.pubspec.dependency_overrides]
jni = "1.1.0"

[tool.flet.android.permission]
"android.permission.POST_NOTIFICATIONS" = true
"android.permission.SCHEDULE_EXACT_ALARM" = true
"android.permission.USE_EXACT_ALARM" = true
"android.permission.WAKE_LOCK" = true
"com.android.alarm.permission.SET_ALARM" = true
"android.permission.RECEIVE_BOOT_COMPLETED" = true
"android.permission.SYSTEM_ALERT_WINDOW" = true
"android.permission.MANAGE_EXTERNAL_STORAGE" = true
"android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" = true

[tool.flet.splash]
color = "#ffffff"
dark_color = "#1B6911"

[tool.flet.app.boot_screen]
show = true
message = "Preparing the app ….."

[tool.flet.app.startup_screen]
show = true
message = "LOADING…"
